GET http://localhost:3721/api/user/list HTTP/1.1
content-type: application/json

{
   "name": "Adobe",
    "Website": "Adobe.com",
    "mes":"1234qwer"
},
{
   "name": "Apple",
    "Website": "Apple.com",
},
{
   "name": "Dirbbble",
    "Website": "Dirbbble.com",
},
{
   "name": "Etsy",
    "Website": "Etsy.com",
},
{
   "name": "Facebook",
    "Website": "Facebook.com",
},
{
   "name": "GooGle",
    "Website": "GooGle.com",
},
{
   "name": "IMDB",
    "Website": "Apple.com",
},
{
   "name": "InVision",
    "Website": "InVision.com",
},
{
   "name": "Telegram",
    "Website": "InVision.com",
},